# Generated by Django 2.1 on 2019-12-11 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20191209_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='question',
        ),
    ]
